name: Reusable Workflow Demo
on:
  workflow_call:
    inputs:
      artifact-name:
        description: "The name of de deployable artifact files"
        required: true
        # default: "dist-files"
        type: string
    secrets:
      token:
        required: true
jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - name: Output information
        run: |
          echo "Deploying to production"
          echo ".... deploying"
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{inputs.artifact-name}}
      - name: Deploy the code
        run: |
          echo "Deploying the code"
          echo "artifact-name: ${{inputs.artifact-name}}"
          echo "secret token: ${{secrets.TOKEN}}"
      - name: Listing files
        run: ls -la
