name: Reusable Workflow Demo
on: workflow_call
jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - name: Output information
        run: |
          echo "Deploying to production"
          echo ".... deploying"
