name: Matrix Demo
on:
  push:
    branches:
      - dev-never-runs
jobs:
  build:
    continue-on-error: true
    strategy:
      matrix:
        node-version: [12, 14, 16, 18]
        os: [ubuntu-24.04, ubuntu-22.04]
        include:
          - node-version: 20
            os: ubuntu-24.04
        exclude:
          - node-version: 12
            os: ubuntu-24.04
          - node-version: 12
            os: ubuntu-22.04
    runs-on: ${{ matrix.os }}
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run build
